#
# This is my laboratory information management system (LIMS)
# Shiny web application
# 
#--------------------------------------------------------------------
# problems:

#  !/Save to group table then general table

#  !/mysql? try to save as .rds but ERROR

#   Edit tables by pop-up window or fixed blanks

#   A button back to initial state
#   Help page


#PROBLEM
# real time login???
# check if it is not unique -> hide button ??


#  !/User permissions
#   Editable permissions???


#---------------------------------------------------------------------

library(shiny)
library(shinydashboard)
library(shinyjs)
library(tidyverse)
library(shinymanager)
library(DT)
library(readr)
library(dplyr)
library(tidyr)
library(shinyFeedback)


# ui
# dashboard_header -------------------------------------------------------------
header <- dashboardHeader(
  #titleWidth = '15%',
  title="My LIMS",
  dropdownMenu(
    type="messages",
    #add Items
    messageItem(
      # message source
      from="system",
      # message content
      message="process finished",
      # icon for the message
      icon=icon(name="envelope")
    )
  )
)



# dashboard_sidebar ------------------------------------------------------------
sidebar <- dashboardSidebar(
  #width = '15%',
  sidebarMenu(
    menuItem("Home", tabName = "home", 
             icon = icon(name="home")),
    menuItem("My Project",tabName = "myproject", icon = icon(name="dna"),
             menuSubItem("Create New Project", 
                      tabName = "create_new_project", 
                      icon = icon(name = "plus-circle")),
             menuSubItem("Projects", 
                      tabName = "current_project", 
                      icon = icon(name = "list")),
             startExpanded = TRUE),
    menuItem("Raw Datasets", tabName = "datasets",icon = icon(name="database"),
             menuSubItem("Create New Dataset", 
                         tabName = "create_new_dataset", 
                         icon = icon(name = "plus-circle")),
             menuSubItem("Datasets", 
                         tabName = "current_dataset", 
                         icon = icon(name = "list")),
             startExpanded = TRUE),
    menuItem("About Us", tabName = "aboutus", 
             icon = icon(name="user-friends")),
    menuItem("FAQ", tabName = "FAQ", 
             icon = icon(name="question-circle")),
    shinyjs::hidden(tags$div(id = 'admin_item',
                             menuItem("Administrator", tabName = "admin",icon = icon(name="user-cog"),
                                      menuSubItem("User Information", ##注册权限信息
                                                  tabName = "admin_user", 
                                                  icon = icon(name = "id-card")),
                                      menuSubItem("Project Option", 
                                                  tabName = "admin_p", 
                                                  icon = icon(name = "search")),
                                      menuSubItem("Dataset Option", 
                                                  tabName = "admin_d", 
                                                  icon = icon(name = "building")),
                                      startExpanded = TRUE)
                                      
                             )
    )
  )
)

# dashboard_body ---------------------------------------------------------------
body <- dashboardBody(
  
  # zoom the web
  tags$style("
    body {
    -moz-transform: scale(0.8, 0.8); /* Moz-browsers */
    zoom: 0.9; /* Other non-webkit browsers */
    zoom: 90%; /* Webkit browsers */
    }
  "),
  
  # ui- Home- Log in page  
  tabItems(
    tabItem(tabName = "home",
            h1("HOME"),
            
            # hide the welcome message at the first place
            shinyjs::hidden(tags$div(
              id = 'tab_login.welcome_div',
              class = 'login-text', 
              textOutput('tab_login.welcome_text', container = tags$h3),
              textOutput('tab_login.permissions_text', container = tags$h3),
              h5('Please contact your administrator if you want to change your permissions.')
              )
            ),
            br(),br(),br(),
            h4("If you have any problems about using this App, please turn to the FAQ page."),
            h4("If the FAQ page does not solve your problem, please contact lims@xx.com. We are very happy to help you!"),
            #verbatimTextOutput("auth_output")
    ),
    
    
    
    tabItem(tabName = "create_new_project",
            h1("PROJECT"),
            
            fluidRow(
              #useShinyFeedback(),
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Create New Project"),
                  box(
                    # automatically generated Proj ID
                    h5("Project ID generated by the system:"),
                    verbatimTextOutput(outputId='proj_id'),###############
                    
                    textInput("projName","Project Name:",placeholder = 'Project Name'),
                    #textInput("projID","Project ID:"),
                    textInput("projParent","Parent Project(optional):"),
                    textInput('projDescription', 'Description:', placeholder = 'You can descrip your project'),
                    dateInput('projDate', 'Start Date:',format = "dd/mm/yyyy",startview = 'month', language = 'en'),
                    dateInput('projDate2', 'End Date:',format = "dd/mm/yyyy",startview = 'month', language = 'en'),
                    textInput('projPath', 'Path:', placeholder = 'Where the project stored in the server'),
                    textInput('projSampleSheet', 'Sample Sheet:', placeholder = 'Sample Sheet'),
                  ),
                  box(
                    textInput('projReport', 'Report(optional):',placeholder = 'Project Report'),
                    selectInput("projResearcher", "Researcher:",
                                c("JCW" = "JCW",
                                  "SL" = "SL",
                                  "Other" = "Other"), selected = 'JCW'),
                    textInput('projBioinformatician', 'Bioinformatician:', placeholder = 'Bioinformatician'),
                    selectInput('projGroup', 'Group:', ######!!!
                                c("Bird" = "Bird",
                                  "Hill" = "Hill",
                                  "Wind" = "Wind",
                                  "Other" = "Other"), selected = 'Bird' ),
                    textInput('projdataRepository', 'Data Repository:', placeholder = 'Data Repository GEO'),
                    textInput('codeRepository', 'Code Repository:', placeholder = 'Code Repository github URL'),
                    selectInput("projStatus", "Status:",
                                c("Complete" = "Complete",
                                  "Published" = "Published",
                                  "Ongoing" = "Ongoing"), selected = 'Ongoing'),
                    selectInput("projPermissions", "Permissions:",
                                c("Group" = "Group",
                                  "Individual" = "Individual",
                                  "Open" = "Open"), selected = 'Group'),
                    actionButton('add_proj', 'Add',
                                 style = "color: white; background-color: teal"),
                    verbatimTextOutput("new_proj_added")
                    )
                  )
              )),
    
    tabItem(tabName = "current_project",
            h1("PROJECT"),
            fluidRow(
              #useShinyFeedback(),
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("My Projects"),
                  h5(),
                  DTOutput(outputId='x1'),   ## projects table
                  #actionButton('save_proj','Save',style = "color: white; background-color: green"),
                  verbatimTextOutput(outputId='y1'), ## list the selected rows and columns / list of current projects
                  actionButton('edit_proj', 'Edit',style = "color: white; background-color: teal"),
                  actionButton('delete_proj', 'Delete',style = "color: white; background-color: red"),
                  #actionButton('save_proj','Save',style = "color: white; background-color: green"),
                  h5(),
                  
                  )),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Related Datasets"),
                  DTOutput(outputId='related_datasets')
                  )),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Parent project and sub-projects"),
                  DTOutput(outputId='parent_sub_proj')
              ))
            ),
            
            
            

    tabItem(tabName = "create_new_dataset",
            h1("DATASET"),
            
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Add New Dataset"),
                  box(
                    h5("Data ID generated by the system:"),
                    verbatimTextOutput(outputId='data_id'),###############
                    # input datasets information
                    #textInput('dataID', 'Data ID:', placeholder = 'Data ID'),
                    textInput('dataprojID', 'Related Project ID(optional):', placeholder = 'Project ID'),
                    textInput('dataName', 'Dataset Name:', placeholder = 'Dataset Name'),
                    textInput('dataDescription', 
                              'Description:', placeholder = 'You can descrip your data'),
                    dateInput('dataDate', 'Date:',format = "dd/mm/yyyy",startview = 'month', language = 'en'),
                    textInput('dataPath', 'Path:', placeholder = 'where the date stored'),
                    textInput('dataRepository', 'Data Repository:', placeholder = 'Data Repository GEO'),
                  ),
                  box(
                    selectInput("method", "Method:",
                                c("ChIP-seq" = "ChIP-seq",
                                  "BS-seq" = "BS-seq"), selected = 'ChIP-seq'),
                    selectInput("organism", "Organism:",
                                c("Human" = "Human",
                                  "Mouse" = "Mouse",
                                  "Other" = "Other"),selected = 'Human'),
                    selectInput("cell", "Tissue/Cell:",
                                c("Brain" = "Brain",
                                  "Neuron" = "Neuron",
                                  "Liver" = "Liver",
                                  "Kidney" = "Kidney",
                                  "Lung" = "Lung",
                                  "Heart" = "Heart",
                                  "Other" = "Other"), selected = 'Brain'),
                    selectInput("genotype", "Genotype:",
                                c("WT(wildtype)" = "WT(wildtype)",
                                  "KO(knock-out)" = "KO(knock-out)",
                                  "TG(transgenic)" = "TG(transgenic)",
                                  "Other" = "Other"), selected = 'WT(wildtype)'),
                    selectInput("format", "Format:",
                                c("fastq" = "fastq",
                                  "fastq.gz" = "fastq.gz",
                                  "BAM" = "BAM",
                                  "Other" = "Other"), selected = 'fastq.gz'),
                    textInput('treatment', 'Treatment:'),
                    actionButton('add_data', 'Add',
                                 style = "color: white; background-color: teal"),
                    verbatimTextOutput("new_data_added")
                  )
              )
            )),
    
    
    tabItem(tabName = "current_dataset",
            h1("DATASET"),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("My Datasets"),
                  h5(),
                  DTOutput(outputId='x2'),  ## the place to output datasets table
                  actionButton('edit_data', 'Edit',style = "color: white; background-color: teal"),
                  actionButton('delete_data', 'Delete',style = "color: white; background-color: red"),
                  #actionButton('save_data','Save',style = "color: white; background-color: green")
                  #verbatimTextOutput(outputId='y2'),  ## the place to output text
              )),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Related Projects"),
                  DTOutput(outputId='related_proj') 
              ))

            
    ),
    
    tabItem(tabName = "aboutus",
            h1("About Us"),
            h5("LIMS is a modularised web-based laboratory information management system built to centrally track projects and data with standardised metadata, while still maintaining appropriate access and permissions to users and groups."), 
            h5("This system will make our analyses more findable, accessible, interoperable and reproducible based on the FAIR data principles.")
    ),
    tabItem(tabName = "FAQ",
            h1("FAQ"),
            h5()
    ),
    
    
    
    tabItem(tabName = "admin_user",
            h1("System Management —— User"),
            h5(),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("User Information"),
                  DTOutput(outputId='admin_user_info') 
              ))
    ),
    tabItem(tabName = "admin_p",
            h1("System Management —— Project Options"),
            h5(),
            fluidRow(
              box(width = 6, height = 630,
                  status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Researcher"), 
                  br(),
                  fluidRow(
                    column(8, textInput('researcherName','Researcher Name:')),
                    column(3, actionButton('add_researcher','Add'))
                  ),
                  #textInput('researcherName','Researcher Name:'),
                  #actionButton('add_researcher','Add'),
                  br(),
                  box(width = 12,
                      DTOutput(outputId='admin_researcher'))
              ),
              box(width = 6,height = 630,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Bioinformatician"), 
                br(),
                fluidRow(
                  column(8, textInput('bioinformaticianName','Bioinformatician Name:')),
                  column(3, actionButton('add_bioinformatician','Add'))
                ),
                br(),
                #textInput('bioinformaticianName','Bioinformatician Name:'),
                #actionButton('add_bioinformatician','Add'),
                box(width = 12,
                    DTOutput(outputId='admin_bioinformatician') )
              ),
              box(width = 6,height = 630,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Group"),
                br(),
                fluidRow(
                  column(8, textInput('groupName','Group Name:')),
                  column(3, actionButton('add_group','Add'))
                ),
                br(),
                #textInput('groupName','Group Name:'),
                #actionButton('add_group','Add'),
                box(width = 12,
                    DTOutput(outputId='admin_group') )
                
              )
            )
    ),
    tabItem(tabName = "admin_d",
            h1("System Management —— Dataset Options"),
            h5(),
            fluidRow(
              box(width = 6,height = 630,
                  status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Method"),
                  br(),
                  fluidRow(
                    column(8, textInput('methodName','Method:')),
                    column(3, actionButton('add_method','Add'))
                  ),
                  br(),
                  DTOutput(outputId='admin_method') 
              ),
              box(width = 6,height = 630,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Organism"),
                br(),
                fluidRow(
                  column(8, textInput('organismName','Organism Name:')),
                  column(3, actionButton('add_organism','Add'))
                ),
                br(),
                DTOutput(outputId='admin_organism') 
              ),
              box(width = 6,height = 630,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Tissue/Cell"),
                br(),
                fluidRow(
                  column(8, textInput('cellName','Tissue/Cell Name:')),
                  column(3, actionButton('add_cell','Add'))
                ),
                br(),
                DTOutput(outputId='admin_cell') 
              ),
              box(width = 6,height = 630,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Genotype"),
                br(),
                fluidRow(
                  column(8, textInput('genotypeName','Genotype Name:')),
                  column(3, actionButton('add_genotype','Add'))
                ),
                br(),
                DTOutput(outputId='admin_genotype') 
              ),
              box(width = 6,height = 630,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Format"),
                br(),
                fluidRow(
                  column(8, textInput('formatName','Format Name:')),
                  column(3, actionButton('add_format','Add'))
                ),
                br(),
                DTOutput(outputId='admin_format') 
              )
            )
    )
  ))

##############
ui <- dashboardPage(
  header,
  sidebar,
  body,
  
  useShinyjs()
)
#ui <- secure_app(ui, choose_language = TRUE)