#
# This is my laboratory information management system (LIMS)
# Shiny web application
# 
#--------------------------------------------------------------------
# problems:

#  !/Save to group table then general table

#  !/mysql? try to save as .rds but ERROR

#   Edit tables by pop-up window or fixed blanks

#   A button back to initial state
#   Help page


#PROBLEM
# real time login???
# check if it is not unique -> hide button ??


#  !/User permissions
#   Editable permissions???


#---------------------------------------------------------------------

library(shiny)
library(shinydashboard)
library(shinyjs)
library(tidyverse)
library(shinymanager)
library(DT)
library(readr)
library(dplyr)
library(tidyr)
library(shinyFeedback)
library(data.table) ## fwrite: fast

# ui
# dashboard_header -------------------------------------------------------------
header <- dashboardHeader(
  #titleWidth = '15%',
  #title="LotusRoot",
  title = tags$img(src = "logo-2.png", height = 60)
  
)



# dashboard_sidebar ------------------------------------------------------------
sidebar <- dashboardSidebar(
  #width = '15%',
  sidebarMenu(
    menuItem("Home", tabName = "home", 
             icon = icon(name="home")),
    menuItem("Projects",tabName = "myproject", icon = icon(name="dna"),
             menuSubItem("Create New Project", 
                      tabName = "create_new_project", 
                      icon = icon(name = "plus-circle")),
             menuSubItem("Projects", 
                      tabName = "current_project", 
                      icon = icon(name = "list")),
             startExpanded = F),
    menuItem("Datasets", tabName = "datasets",icon = icon(name="database"),
             menuSubItem("Create New Dataset", 
                         tabName = "create_new_dataset", 
                         icon = icon(name = "plus-circle")),
             menuSubItem("Datasets", 
                         tabName = "current_dataset", 
                         icon = icon(name = "list")),
             startExpanded = F),
    
    menuItem("About Us", tabName = "aboutus", 
             icon = icon(name="user-friends")),
    menuItem("FAQ", tabName = "FAQ", 
             icon = icon(name="question-circle")),
    
    shinyjs::hidden(tags$div(
      id = 'admin_item',
      menuItem("Administrator", tabName = "admin",icon = icon(name="user-cog"),
               menuSubItem("User Information",
                           tabName = "admin_user", 
                           icon = icon(name = "id-card")),
               menuSubItem("Project Options", 
                           tabName = "admin_p", 
                           icon = icon(name = "search")),
               menuSubItem("Dataset Options", 
                           tabName = "admin_d", 
                           icon = icon(name = "building")),
               startExpanded = F)
    )
    )
    
  )
)

# dashboard_body ---------------------------------------------------------------
body <- dashboardBody(
  
  # zoom the web
  tags$style("
    body {
    -moz-transform: scale(0.8, 0.8); /* Moz-browsers */
    zoom: 0.9; /* Other non-webkit browsers */
    zoom: 90%; /* Webkit browsers */
    }
  "),
  
  # ui- Home- Log in page  
  tabItems(
    tabItem(tabName = "home",
            h1("HOME"),
            
            # hide the welcome message at the first place
            shinyjs::hidden(tags$div(
              id = 'tab_login.welcome_div',
              class = 'login-text', 
              textOutput('tab_login.welcome_text', container = tags$h3),
              textOutput('tab_login.permissions_text', container = tags$h3),
              h5('Please contact your administrator if you want to change your permissions.')
              )
            ),
            br(),br(),br(),
            h5("If you have any problems about using this App, please turn to the FAQ page."),
            h5("If the FAQ page does not solve your problem, please contact s2045156@ed.ac.uk. We are very happy to help you!"),
            #verbatimTextOutput("auth_output")
            br(),
            h5("Related Links:"),
            uiOutput("links")
    ),
    
    
    
    tabItem(tabName = "create_new_project",
            h1("PROJECT"),
            
            fluidRow(
              #useShinyFeedback(),
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Create New Project"),
                  box(
                    # automatically generated Proj ID
                    h5("Project ID generated by the system:"),
                    verbatimTextOutput("proj_id"), ## not display id??
                    textInput("projName","Project Name:",placeholder = 'Project Name (eg. BioCenter_Lucy_2021)'),
                    #textInput("projID","Project ID:"),
                    #textInput("projParent","Parent Project(optional):"),
                    #selectInput("projParent","Parent Project(optional):")
                    uiOutput("proj_parent"),
                    textInput('projDescription', 'Description:', placeholder = 'Brief description of your project'),
                    dateInput('projDate', 'Start Date:',format = "dd/mm/yyyy",startview = 'month', language = 'en'),
                    #dateInput('projDate2', 'End Date:',format = "dd/mm/yyyy",startview = 'month', language = 'en'),
                    textInput('projPath', 'Path(optional):', placeholder = 'Where the project stored on the server/URL'),
                    textInput('projSampleSheet', 'Sample Sheet(optional):', placeholder = 'Path/URL where the sample sheet stored'),
                    textInput('projReport', 'Report(optional):',placeholder = 'Path/URL where the project report stored')
                  ),
                  box(
                    uiOutput("proj_researcher"),
                    uiOutput("proj_bioinfo"),
                    uiOutput("proj_group"),
                    textInput('projdataRepository', 'Data Repository:', placeholder = 'web address/GEO number(eg. GEO10000)'),
                    textInput('codeRepository', 'Code Repository:', placeholder = 'Where your code stored (eg.GitHub URL / path'),
                    selectInput("projStatus", "Status:",
                                c("Complete" = "Complete",
                                  "On Hold"="On Hold",              ## different colours:blue,gray,green,yellow
                                  "Published" = "Published",
                                  "Ongoing" = "Ongoing"), selected = 'Ongoing'),
                    
                    selectInput("projPermissions", "Permissions:",
                                c("Group" = "Group",
                                  "Individual" = "Individual",
                                  "Open" = "Open"), selected = 'Group'),
                    actionButton('add_proj', 'Add',
                                 style = "color: white; background-color: teal"),
                    verbatimTextOutput("new_proj_added")
                    )
                  )
              )),
    
    tabItem(tabName = "current_project",
            h1("PROJECT"),
            fluidRow(
              #useShinyFeedback(),
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Project Table"),
                  h5(),
                  DTOutput(outputId='x1'),   ## projects table
                  #verbatimTextOutput(outputId='y1'), ## list the selected rows and columns / list of current projects
                  actionButton('edit_proj', 'Edit',style = "color: white; background-color: teal"),
                  actionButton('delete_proj', 'Delete',style = "color: white; background-color: red"),
                  actionButton('clear_selected_proj', 'Clear selected',style = "color: white; background-color: green"),
                  h5(),
                  )),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Related Datasets"),
                  DTOutput(outputId='related_datasets')
                  )),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Related Projects"),
                  DTOutput(outputId='parent_sub_proj')
              ))
            ),
            
            
            

    tabItem(tabName = "create_new_dataset",
            h1("DATASET"),
            
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Add New Dataset"),
                  box(
                    h5("Data ID generated by the system:"),
                    verbatimTextOutput(outputId='data_id'),
                    #textInput('dataID', 'Data ID:', placeholder = 'Data ID'),
                    #textInput('dataprojID', 'Related Project Name(optional):', placeholder = 'Project ID'),
                    uiOutput("related_project_name"),
                    textInput('dataName', 'Dataset Name:', placeholder = 'eg. mCG_BS_WT1, mCG_BS_WT1'),
                    textInput('dataDescription', 
                              'Description:', placeholder = 'Brief description of your dataset'),
                    dateInput('dataDate', 'Date:',format = "dd/mm/yyyy",startview = 'month', language = 'en'),
                    textInput('dataPath', 'Path(optional):', placeholder = 'Where the data stored on the server/URL'),
                    textInput('dataRepository', 'Data Repository:', placeholder = 'web address/GEO number(eg. GEO10000)'),
                  ),
                  box(
                    selectInput("method", "Method:",
                                choices = am_method[,1]),
                    selectInput("organism", "Organism:",
                                choices = am_organism[,1]),
                    selectInput("cell", "Tissue/Cell:",
                                choices = am_cell[,1]),
                    textInput("genotype", "Genotype:",placeholder = 'eg. wildtype, knock-out...'),
                    selectInput("format", "Format:",
                                choices = am_format[,1]),
                    #textInput('treatment', 'Treatment:'),
                    actionButton('add_data', 'Add',
                                 style = "color: white; background-color: teal"),
                    verbatimTextOutput("new_data_added")
                  )
              )
            )),
    
    
    tabItem(tabName = "current_dataset",
            h1("DATASET"),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Datasets"),
                  h5(),
                  DTOutput(outputId='x2'),  ## the place to output datasets table
                  actionButton('edit_data', 'Edit',style = "color: white; background-color: teal"),
                  actionButton('delete_data', 'Delete',style = "color: white; background-color: red"),
                  actionButton('clear_selected_data', 'Clear selected',style = "color: white; background-color: green")
              )),
            fluidRow(
              box(width = 12,status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Related Projects"),
                  DTOutput(outputId='related_proj') 
              ))

            
    ),
    
    tabItem(tabName = "aboutus",
            h1("About Us"),
            h5("LIMS is a modularised web-based laboratory information management system built to centrally track projects and data with standardised metadata, while still maintaining appropriate access and permissions to users and groups."), 
            h5("This system will make our analyses more findable, accessible, interoperable and reproducible based on the FAIR data principles.")
    ),
    tabItem(tabName = "FAQ",
            h1("FAQ"),
            h5()
    ),
    
    
    
    tabItem(tabName = "admin_user",
            h1("System Management —— User"),
            h5(),
            fluidRow(
              box(width = 12,
                  status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("User Information"),
                  fluidRow(
                    column(4, textInput('userName','Username',placeholder = "Please enter full name")),
                    column(4, passwordInput('userPW','Password')),
                    column(4, textInput("userEmail", "Email :")),
                    uiOutput("admin_user_group"),
                    column(4, selectInput(inputId = "userPermissions", "User Permissions:", 
                                          choices = c('General_Staff','Data_Administrator','Project_Supervisor ','System_Maintenance')
                                          )),
                    column(5,offset = 0, actionButton('add_user','Add',style = "color: white; background-color: teal")),
                    column(5,verbatimTextOutput("user_successfully_added"))
                  ),
                  br(),
                  box(width = 12, 
                      DTOutput(outputId='admin_user_info'),
                      actionButton('delete_user','Delete',style = "color: white; background-color: red"))
              ))
    ),
    tabItem(tabName = "admin_p",
            h1("System Management —— Project Options"),
            h5(),
            fluidRow(
              
              box(width = 6, height = 850,
                  status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Researcher"), ###
                  br(),
                  fluidRow(
                    column(8, textInput('researcherName','Name:')),
                    column(3, actionButton('add_researcher','Add',style = "color: white; background-color: teal"))
                  ),
                  verbatimTextOutput("researcher_successfully_added"),
                  br(),
                  box(width = 12,
                      DTOutput(outputId='admin_researcher'),
                      actionButton('delete_researcher','Delete',
                                   style = "color: white; background-color: red")
                      )
              ),
              #box(width = 6,height = 670,
              #  status = "primary",collapsible = FALSE,solidHeader = TRUE,
              #  h3("Bioinformatician"), ###
              #  br(),
              #  fluidRow(
              #    column(8, textInput('bioinformaticianName','Bioinformatician Name:')),
              #    column(3, actionButton('add_bioinformatician','Add',style = "color: white; background-color: teal"))
              #  ),
              #  verbatimTextOutput("bioinformatician_successfully_added"),
              #  br(),
              #  box(width = 12,
              #      DTOutput(outputId='admin_bioinformatician'),
              #      actionButton('delete_bioinformatician','Delete',
              #                   style = "color: white; background-color: red")
              #      )
              #),
              box(width = 6,height = 850,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Group"),###
                br(),
                fluidRow(
                  column(8, textInput('groupName','Group Name:')),
                  column(3, actionButton('add_group','Add',style = "color: white; background-color: teal"))
                ),
                verbatimTextOutput("group_successfully_added"),
                br(),
                box(width = 12,
                    DTOutput(outputId='admin_group'),
                    actionButton('delete_group','Delete',
                                 style = "color: white; background-color: red")
                    )
              )
            )
    ),
    tabItem(tabName = "admin_d",
            h1("System Management —— Dataset Options"),
            h5(),
            fluidRow(
              box(width = 6,height = 850,
                  status = "primary",collapsible = FALSE,solidHeader = TRUE,
                  h3("Method"),
                  br(),
                  fluidRow(
                    column(8, textInput('methodName','Method:')),
                    column(3, actionButton('add_method','Add',style = "color: white; background-color: teal"))
                  ),
                  verbatimTextOutput("method_successfully_added"),
                  br(),
                  box(width = 12,
                      DTOutput(outputId='admin_method'),
                      actionButton('delete_method','Delete',
                                   style = "color: white; background-color: red")
                  )
              ),
              box(width = 6,height = 850,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Organism"),
                br(),
                fluidRow(
                  column(8, textInput('organismName','Organism Name:')),
                  column(3, actionButton('add_organism','Add',style = "color: white; background-color: teal"))
                ),
                verbatimTextOutput("organism_successfully_added"),
                br(),
                box(width = 12,
                    DTOutput(outputId='admin_organism'),
                    actionButton('delete_organism','Delete',
                                 style = "color: white; background-color: red")
                )
              ),
              box(width = 6,height = 850,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Tissue/Cell"),
                br(),
                fluidRow(
                  column(8, textInput('cellName','Tissue/Cell Name:')),
                  column(3, actionButton('add_cell','Add',style = "color: white; background-color: teal"))
                ),
                verbatimTextOutput("cell_successfully_added"),
                br(),
                box(width = 12,
                    DTOutput(outputId='admin_cell'),
                    actionButton('delete_cell','Delete',
                                 style = "color: white; background-color: red")
                )
              ),
              box(width = 6,height = 850,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Genotype"),
                br(),
                fluidRow(
                  column(8, textInput('genotypeName','Genotype Name:')),
                  column(3, actionButton('add_genotype','Add',style = "color: white; background-color: teal"))
                ),
                verbatimTextOutput("genotype_successfully_added"),
                br(),
                box(width = 12,
                    DTOutput(outputId='admin_genotype'),
                    actionButton('delete_genotype','Delete',
                                 style = "color: white; background-color: red")
                )
              ),
              box(width = 6,height = 850,
                status = "primary",collapsible = FALSE,solidHeader = TRUE,
                h3("Format"),
                br(),
                fluidRow(
                  column(8, textInput('formatName','Format Name:')),
                  column(3, actionButton('add_format','Add',style = "color: white; background-color: teal"))
                ),
                verbatimTextOutput("format_successfully_added"),
                br(),
                box(width = 12,
                    DTOutput(outputId='admin_format'),
                    actionButton('delete_format','Delete',
                                 style = "color: white; background-color: red")
                )
                
              )
            )
    )
    
    
  )
)
  

##############
ui <- dashboardPage(
  skin = "black",
  header,
  sidebar,
  body,
  
  useShinyjs()
)
#ui <- secure_app(ui, choose_language = TRUE)